services:
  #maku-generator
  maku-generator:
    image: zerfa/maku-generator:3.1.0
#    restart: always
    container_name: maku-generator
    networks:
      network:
        ipv4_address: 172.18.0.188
#    ports:
#      - 3307:8088
    environment:
      DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DATASOURCE_URL: jdbc:mysql://mysql:3306/maku_generator?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      DATASOURCE_NAME: root
      DATASOURCE_PASSWORD: 123456




networks:
  network:
    external: true